// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: proto/tracker.proto

package rpc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type InfoHashParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InfoHash []byte `protobuf:"bytes,1,opt,name=info_hash,json=infoHash,proto3" json:"info_hash,omitempty"`
}

func (x *InfoHashParam) Reset() {
	*x = InfoHashParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tracker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoHashParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoHashParam) ProtoMessage() {}

func (x *InfoHashParam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tracker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoHashParam.ProtoReflect.Descriptor instead.
func (*InfoHashParam) Descriptor() ([]byte, []int) {
	return file_proto_tracker_proto_rawDescGZIP(), []int{0}
}

func (x *InfoHashParam) GetInfoHash() []byte {
	if x != nil {
		return x.InfoHash
	}
	return nil
}

type Torrent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TorrentId int64     `protobuf:"varint,1,opt,name=torrent_id,json=torrentId,proto3" json:"torrent_id,omitempty"`
	InfoHash  []byte    `protobuf:"bytes,2,opt,name=info_hash,json=infoHash,proto3" json:"info_hash,omitempty"`
	Name      string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Seeders   int32     `protobuf:"varint,4,opt,name=seeders,proto3" json:"seeders,omitempty"`
	Leechers  int32     `protobuf:"varint,5,opt,name=leechers,proto3" json:"leechers,omitempty"`
	Time      *TimeMeta `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *Torrent) Reset() {
	*x = Torrent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tracker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Torrent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Torrent) ProtoMessage() {}

func (x *Torrent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tracker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Torrent.ProtoReflect.Descriptor instead.
func (*Torrent) Descriptor() ([]byte, []int) {
	return file_proto_tracker_proto_rawDescGZIP(), []int{1}
}

func (x *Torrent) GetTorrentId() int64 {
	if x != nil {
		return x.TorrentId
	}
	return 0
}

func (x *Torrent) GetInfoHash() []byte {
	if x != nil {
		return x.InfoHash
	}
	return nil
}

func (x *Torrent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Torrent) GetSeeders() int32 {
	if x != nil {
		return x.Seeders
	}
	return 0
}

func (x *Torrent) GetLeechers() int32 {
	if x != nil {
		return x.Leechers
	}
	return 0
}

func (x *Torrent) GetTime() *TimeMeta {
	if x != nil {
		return x.Time
	}
	return nil
}

type TorrentParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TorrentID int64 `protobuf:"varint,1,opt,name=torrentID,proto3" json:"torrentID,omitempty"`
}

func (x *TorrentParams) Reset() {
	*x = TorrentParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tracker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TorrentParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorrentParams) ProtoMessage() {}

func (x *TorrentParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tracker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorrentParams.ProtoReflect.Descriptor instead.
func (*TorrentParams) Descriptor() ([]byte, []int) {
	return file_proto_tracker_proto_rawDescGZIP(), []int{2}
}

func (x *TorrentParams) GetTorrentID() int64 {
	if x != nil {
		return x.TorrentID
	}
	return 0
}

type TorrentAddParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	InfoHash []byte  `protobuf:"bytes,2,opt,name=info_hash,json=infoHash,proto3" json:"info_hash,omitempty"`
	MultiUp  float64 `protobuf:"fixed64,3,opt,name=multi_up,json=multiUp,proto3" json:"multi_up,omitempty"`
	MultiDn  float64 `protobuf:"fixed64,4,opt,name=multi_dn,json=multiDn,proto3" json:"multi_dn,omitempty"`
}

func (x *TorrentAddParams) Reset() {
	*x = TorrentAddParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tracker_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TorrentAddParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorrentAddParams) ProtoMessage() {}

func (x *TorrentAddParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tracker_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorrentAddParams.ProtoReflect.Descriptor instead.
func (*TorrentAddParams) Descriptor() ([]byte, []int) {
	return file_proto_tracker_proto_rawDescGZIP(), []int{3}
}

func (x *TorrentAddParams) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TorrentAddParams) GetInfoHash() []byte {
	if x != nil {
		return x.InfoHash
	}
	return nil
}

func (x *TorrentAddParams) GetMultiUp() float64 {
	if x != nil {
		return x.MultiUp
	}
	return 0
}

func (x *TorrentAddParams) GetMultiDn() float64 {
	if x != nil {
		return x.MultiDn
	}
	return 0
}

type TorrentUpdateParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Deleted bool   `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Enabled bool   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Reason  string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	MultiUp string `protobuf:"bytes,5,opt,name=multi_up,json=multiUp,proto3" json:"multi_up,omitempty"`
	MultiDn string `protobuf:"bytes,6,opt,name=multi_dn,json=multiDn,proto3" json:"multi_dn,omitempty"`
}

func (x *TorrentUpdateParams) Reset() {
	*x = TorrentUpdateParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tracker_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TorrentUpdateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorrentUpdateParams) ProtoMessage() {}

func (x *TorrentUpdateParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tracker_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorrentUpdateParams.ProtoReflect.Descriptor instead.
func (*TorrentUpdateParams) Descriptor() ([]byte, []int) {
	return file_proto_tracker_proto_rawDescGZIP(), []int{4}
}

func (x *TorrentUpdateParams) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TorrentUpdateParams) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *TorrentUpdateParams) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *TorrentUpdateParams) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TorrentUpdateParams) GetMultiUp() string {
	if x != nil {
		return x.MultiUp
	}
	return ""
}

func (x *TorrentUpdateParams) GetMultiDn() string {
	if x != nil {
		return x.MultiDn
	}
	return ""
}

var File_proto_tracker_proto protoreflect.FileDescriptor

var file_proto_tracker_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x69, 0x6b, 0x61, 0x1a, 0x12, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x2c, 0x0a, 0x0d, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x61, 0x73, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x08, 0x69, 0x6e, 0x66, 0x6f, 0x48, 0x61, 0x73, 0x68, 0x22, 0xb3, 0x01,
	0x0a, 0x07, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74,
	0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x66, 0x6f,
	0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x69, 0x6e, 0x66,
	0x6f, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x65,
	0x64, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x65, 0x65, 0x64,
	0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x65, 0x65, 0x63, 0x68, 0x65, 0x72, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6c, 0x65, 0x65, 0x63, 0x68, 0x65, 0x72, 0x73, 0x12,
	0x22, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x6d, 0x69, 0x6b, 0x61, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x22, 0x2d, 0x0a, 0x0d, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x49, 0x44, 0x22, 0x79, 0x0a, 0x10, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e,
	0x66, 0x6f, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x69,
	0x6e, 0x66, 0x6f, 0x48, 0x61, 0x73, 0x68, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x75, 0x6c, 0x74, 0x69,
	0x5f, 0x75, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x6d, 0x75, 0x6c, 0x74, 0x69,
	0x55, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x5f, 0x64, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x44, 0x6e, 0x22, 0xab, 0x01,
	0x0a, 0x13, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x5f, 0x75,
	0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x55, 0x70,
	0x12, 0x19, 0x0a, 0x08, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x5f, 0x64, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x44, 0x6e, 0x42, 0x24, 0x5a, 0x22, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x65, 0x69, 0x67, 0x68, 0x6d,
	0x61, 0x63, 0x64, 0x6f, 0x6e, 0x61, 0x6c, 0x64, 0x2f, 0x6d, 0x69, 0x6b, 0x61, 0x2f, 0x72, 0x70,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_tracker_proto_rawDescOnce sync.Once
	file_proto_tracker_proto_rawDescData = file_proto_tracker_proto_rawDesc
)

func file_proto_tracker_proto_rawDescGZIP() []byte {
	file_proto_tracker_proto_rawDescOnce.Do(func() {
		file_proto_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_tracker_proto_rawDescData)
	})
	return file_proto_tracker_proto_rawDescData
}

var file_proto_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_tracker_proto_goTypes = []interface{}{
	(*InfoHashParam)(nil),       // 0: mika.InfoHashParam
	(*Torrent)(nil),             // 1: mika.Torrent
	(*TorrentParams)(nil),       // 2: mika.TorrentParams
	(*TorrentAddParams)(nil),    // 3: mika.TorrentAddParams
	(*TorrentUpdateParams)(nil), // 4: mika.TorrentUpdateParams
	(*TimeMeta)(nil),            // 5: mika.TimeMeta
}
var file_proto_tracker_proto_depIdxs = []int32{
	5, // 0: mika.Torrent.time:type_name -> mika.TimeMeta
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_tracker_proto_init() }
func file_proto_tracker_proto_init() {
	if File_proto_tracker_proto != nil {
		return
	}
	file_proto_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_tracker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoHashParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tracker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Torrent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tracker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TorrentParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tracker_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TorrentAddParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tracker_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TorrentUpdateParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_tracker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_tracker_proto_goTypes,
		DependencyIndexes: file_proto_tracker_proto_depIdxs,
		MessageInfos:      file_proto_tracker_proto_msgTypes,
	}.Build()
	File_proto_tracker_proto = out.File
	file_proto_tracker_proto_rawDesc = nil
	file_proto_tracker_proto_goTypes = nil
	file_proto_tracker_proto_depIdxs = nil
}
