#!/usr/bin/env bash
echo "Running go fmt..."
make fmt

echo "Running go vet..."
vetcount=`go vet . 2>&1 | wc -l`
if [ $vetcount -gt 0 ]; then
    echo "Some files aren't passing vet heuristics, please run 'go vet .' to see the errors it flags and correct your source code before committing"
    exit 1
fi
exit 0
